sonar.projectKey=hiruniwijendrasinhe_House_hold_job_frondend
sonar.organization=hiruniwijendrasinhe
sonar.projectName=HouseHoldJob Frontend
sonar.sources=./src
sonar.exclusions=**/node_modules/**,**/*.md,**/build/**,**/dist/**
sonar.sourceEncoding=UTF-8
